# Maintainer: Thomas Gingele (https://github.com/B1TC0R3)
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=hash-cmp-bin
pkgver=4.0.0
pkgrel=1
pkgdesc="Validates the hash of a file against a known hash"
url="https://github.com/B1TC0R3/hash-cmp"
license=("GPL-3.0")
arch=("x86_64")
provides=("hash-cmp")
conflicts=("hash-cmp")
source=("https://github.com/B1TC0R3/hash-cmp/releases/download/v$pkgver/hash-cmp-$pkgver-x86_64.tar.gz")
sha256sums=("7ebd00f601ab2b239987068c32ccdb089320e6adff2e4ffbd1cf78bcec0b5a5b")

package() {
    install -Dm755 hash-cmp -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
